/**
 * Copyright (c) 2023 Enzien Audio, Ltd.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions, and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the phrase "powered by heavy",
 *    the heavy logo, and a hyperlink to https://enzienaudio.com, all in a visible
 *    form.
 * 
 *   2.1 If the Application is distributed in a store system (for example,
 *       the Apple "App Store" or "Google Play"), the phrase "powered by heavy"
 *       shall be included in the app description or the copyright text as well as
 *       the in the app itself. The heavy logo will shall be visible in the app
 *       itself as well.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */

#ifndef _HEAVY_CONTEXT_GRILLOSYCHICHARRASOSC_HPP_
#define _HEAVY_CONTEXT_GRILLOSYCHICHARRASOSC_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvSignalBiquad.h"
#include "HvMath.h"
#include "HvSignalPhasor.h"
#include "HvControlUnop.h"
#include "HvControlSlice.h"
#include "HvControlBinop.h"
#include "HvControlSystem.h"
#include "HvSignalLine.h"
#include "HvControlRandom.h"
#include "HvSignalVar.h"
#include "HvControlIf.h"
#include "HvControlCast.h"
#include "HvControlDelay.h"
#include "HvControlVar.h"

class Heavy_grillosychicharrasosc : public HeavyContext {

 public:
  Heavy_grillosychicharrasosc(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_grillosychicharrasosc();

  const char *getName() override { return "grillosychicharrasosc"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        BUTTON1 = 0xFB2DC5B6, // button1
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cSwitchcase_Cbwk7oy4_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_Yu8ay0lQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vH7CHwhb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RWQj5MQd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_QuSBQYIg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Nnfc7x9C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XuD0Af2d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dWrblezy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A6MVYCVF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_whoE78sD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_P3KL6noN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_eUIKfLve_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_7lFwUGAG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_UGP0k8lj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_hOFE8kyf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WuU3C4Lp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mSey5KC8_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_7NQTkXJf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_QRu4amnD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_v7pWLsoa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_TQ5jAajU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XX4B0Ylm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_MvzFBJsX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ObOUWnoI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_mKyLpCkL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_n2TyQRTN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SQRUBity_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3iEOSrVd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_gi6wfGWj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_rSCzT55f_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_u22bsNJt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2KYMBCXH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ys5vXoGF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_8JCiD3xu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_VuUO8pOT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_q79nJAh7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GUwf6car_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lEGH7x11_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_V9kkKiuu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_b7X8kTRD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1gnwmFKC_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_I9HGiHfh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0Cq6OON0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_jMqHt8CW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_suiSbvgo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_gQaBz8x0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_1Go5tnsh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XyTmFvhx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_dJJFMQQg_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_rfoxT6AR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yUmE2zKD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_kumb9KeP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_IaKoKe7K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_AUvEPHcH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_9901yvQJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_miFiRetk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MnWPJHoa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OfvUtCed_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RwHb5AJR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DqCOIhPF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MLSWh2ar_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nt8XXNDD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_K7HGzSWC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6HWKc81T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mV5g0T3w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2EhbrWuc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_n7BdOojc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jj0I2Gyy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QW4mOUH0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LkvaFqZl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Q2oXPhBt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZbtC0Rmd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Cq97QXLx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LwIxeSF8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AstJS1GT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xvEgfs4S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E9AObh1O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_asUbGycQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RaaKDN2X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6x8OpbvE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DS1seFj6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_B5PReqbP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sTIyL0PO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_apMnaPfX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_0E56Ry9P_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_07Fccqhv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_W4LTFttb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_cBjjgoSs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_sZfVq8jD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_waQ539xS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_OHJwD2Ih_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9qp5BItd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_R45Qg3wP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Vktpfbd8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LwzhYklL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_g0xgEbCg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6vxLx8Vr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LYXvGp3l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Wsj5boRx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eogoMDMN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_K7ebZwft_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YvzUZ60u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5rhoA3ga_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eRBgk2p4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OAggoaE2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sBYYDrxv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yip3Mvj2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_c0YyRIgN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wmR3cs6y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_shVLnjCS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NYxrAlj3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KWQ8SFiE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vlwLyyMZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Q2YtODBe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_FXYnpodj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_3RJCOYcc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Vr5tWdRJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_M5qb9FJm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_6UaQ42gt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cZOROno5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_J14XC6HZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_S6u3ul1z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yDPQIzrg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PKYneWMg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bfBrGQS9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_5y7LJokT_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_IALkIGZq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_olTf5TCP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ndDSPe0t_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_b5EiwBH6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_JQV7rzsL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_RNwsu7Qp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TqsPRgvJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_SOXreitf_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_OoKTuXfx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_USNPbtPW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FA9HM06u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_68g9fpZP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_9Rcv20sv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_H5REGhA3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HOIkovc2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NWGmmZbL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HkobI4YQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LgjHNIXb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Id4eDgmg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_g8b8l7i3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zKMxahOq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8KP0bSZt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sYjQzHyd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_U8PTT4zA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kHEXUx6A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SKzc1gku_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QeDD2wjJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LoWJZoQf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JqPRFbjn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qO9ClLqz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eAvouhNx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aVLrzYKi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_G2p8G4dJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QsbALApc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YrgDY46N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EWKnOX91_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9Gc7fXz6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Z3lEbYEy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hBWMRujS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_x9CLsONl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2dLqX6Uz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lJd1a9G1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wYXJkuu3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7XMFG1Jx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4SrcHYHo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ndzgTe5o_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_PFXxURNb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ywPAqYuv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_PCO0VYX9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_LZtWDIcT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_dSh8jpV1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_JF0BuKA0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_77b0Z3qh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_AZjTkGDB_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_idOZvx7g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_0SiIPBmq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_i9t3pPrX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_khUFGaEr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lJiJqIrv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uqRlI22G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_M9qFHYXJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_p7OdiHgQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lkhoEbFH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_L94Uxz5Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_mMKWm5bv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_MBFODPm4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_262Ji6rS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9vXMw8jJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UoyEAKfN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0QS5SfF7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pQzBDdyv_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_tLBIwWgs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_pKlIlXfO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_2so6wfvk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_0bPF1CDO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7XYtZaPr_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_Cyt5ljfN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7wQgkZA8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mq9mNoep_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_aqddLF7P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_KZzpRZHu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YHMVHhtc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ax2bMkL6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vfQSCO7E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EaLgdUhr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_NYogtbpd_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_VSHSmeue_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_GwbmXk9G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_YHJH6zTc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_H8WLX0Iq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_bPVGaSha_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_K87lg2Hy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_tvmSOMPn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_PiQsvku9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_jIX7xxc7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_p6ysPqau_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fNoxrzOT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_yIKEkqJb_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_PqaUaY8t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2sSdeL2o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LhmEaKsR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_x30WhkBe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QQ3c7mjd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mcNBLSnI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LnBVPhpy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SivKmNdC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0EEBEXb9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_OIqXkG1F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_dzAK6N91_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_XnLeU43m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2idDL7H2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_XTbeg9bg_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_5Qo8DRgA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_8dT8qj1B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_L86GS0rj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pOgk2fvX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1xin6sLZ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_O8Hz0Abw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rRmXwkhu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_hdQhtWbh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BGG0hetm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_y08LbGNS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_ov2A0O1C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zkut63Cf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_96fhtK7S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_quEGVJ1U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QoV1xBwp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Y9zFco5H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ObZXda0t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_d0ISqZnl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_f28B4zty_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ea3HLll1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zeg3ioTW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_khxlaUhk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0Zhcg7Yj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5TUORvyu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QwN4hcs7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fz4B2R0F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jVJK1QaI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HVzaY7BS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5P1Hb7z4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tCM7NJzz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zYn8oOMA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NQ2cqRZG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fx59ifmX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gZMON85b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Gqj0ryco_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MuUhe7YQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_71qBrZnH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L9XikDLN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XOJVBFJe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NXTkXCSs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MmUXlvgn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_OwvzQoYk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_s8NSUgUT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AJdW1FPq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QubbZ0D8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6UkvfsRs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xi3LmSMS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BjPyovvN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_j9PNCChJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_YKbiM2Yc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ag7ixMZ3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Kstu0Sqb_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_9cTclMV7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BFhDUGdS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RQtgzNmD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_LWwHKmvR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AVMDlWey_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IeCZWF9q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YHtR9sI5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZYlNZIe7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hkTMVp8Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ottfoJXb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BI6RTa4n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_JRFly6Hw_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_gRRCpeNl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yCRKlYhO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kTkKM3lN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_nmH9dcXV_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_li9JZJAJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UxxCBAm2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Jq4NC0G9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_6ESnmxbt_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_bDp0Em7l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_t4IRbPTR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sFIJQhen_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ZIJ4W7mW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_KYdtSpcr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JAF9aq0A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HCoUAokI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_DO95o62p_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_QrGvT5Yt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NOEJplFD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_x8Nl8tQI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_RyT5ZXVQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_nvxwvLIr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WGhcCpSe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oPDXrTDJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7qmFv4m2_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_S5MaK3OA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qf5Y3e97_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OGDc7kV1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8CyP6UBV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qoAHRdJi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_u2p8tCx9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HkiDCFMJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4VgONu0p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_a8yLBkSB_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_kLoEC4eE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tSAO1GqL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kcO1FnU0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_rS9Noy4a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_U4EkIXYq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E1uwUDIp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Xh1pArzI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_raPv7gtG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DF6o1oSK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_FtUTs4zj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_ElIMyhI4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TNvjw0Dv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2VlMbUbv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_sgMtOFhI_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_OBSHeIX0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ZQJscbhm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_NjsBlyXK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_pFc3oYz0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_84idmOMj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_5umfRAyp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tngapHCw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XOFJBKrB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ZjVhKfR8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pS2KruIk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WFJPLhdD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R30E2bCV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EK0xFzzX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_chgNfAfk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_V503mQR2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cJmF00rT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1PZetlpz_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_J1E6pX7q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DxlzWABp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iRRDEkAR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_I3lWjcEm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AFG1TkyL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_tActedTf_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_CqpVnGSo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Ablg45kn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_j8IJW7sl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_pZkf2HDY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_17VP22zG_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_41evEucb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_92bjR1cG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SV5aDU0X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ypo4ingG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_1Oz9TWlk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_HGWyZfQk_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_CZ43RpKE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RaZJZmvw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TsKNQGgZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_MbWwxM0i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_sgz0sbH8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ql3UBbmu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ic3FAA6P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CAWdFQ4V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZnzomJYv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_y46Bm6Zu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_3uhvegNS_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_6uxqwjiH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8yhx1Npx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_KUSUXSCG_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_psW4eCG8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_7m0Inwpv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_A9IDcNzF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_v7M1WUqA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_v3nlIKKL_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_TH8lc9hP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lzt4oFBo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_RNoZ0NsK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_EZN8BtLf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_HemW1RcB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_MEWQBFaB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aFhbokg6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p1hgJmgs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bIceu0a5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Q8hCu2ql_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DViOseny_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GHVf6mf8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KjNFx3u3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zo1wzf0f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9G2yErcz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rv88LeR6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QuUF7Uto_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5krcrkWQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0QnbITFr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_77hkn075_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_B0cgen1l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eZFq3xOR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_H20LG1xg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8zEWHjmM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Njw4S64e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_86JKvPAP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5VXiDuXB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SP1OHu8E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZBGL1L65_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oXfbQjHp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2zVoIiD2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qv5EJqbZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3DQu3LKQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QFcaq8s1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yxSrksL3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_kXjW19El_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_JFylwJxp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_zbnjIPXp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_GbGZkESD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_I86YF72x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_cYet3INk_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_a5wfCUjy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_R84Z2oq8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JYsQVmzn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_iVsW13E1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_PyhZPnaU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HsOWXSIB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VT7Ojn4h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jHFUXb03_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Gk65LOcD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YrGju7j8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JuTMwHW7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_RkfCb5PP_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_7U1bb9hT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XtSXhodI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HLJGbWmI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZZUedFlg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Iq8wPRXE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_XozGNktq_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_5PvoTscH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_Wp5EFefg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_psO9A26B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_ecqJ4sfE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_XPlfbjP2_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_2vxR4c2p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WnUscKg8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_M5FzdTSj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_O2hLJNtL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_mEHrCKVt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YxHvxcXE_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_pIKdjt2k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mM5UXZhs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VbzQyZsc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_9lAUyyFV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HZC1ip7W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jNid9xwK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Vz02BJP2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5l3EpQ0c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NmPYD90t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_eOO7M87x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_DVxfVyKA_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_xGZDr5Uo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rYo2LH85_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_8N9H8BR4_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_xWoOn2P4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_35rqWCye_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8np9dfCS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yC2Epoyf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_LtBibLJq_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_hvn0Mv1j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_tPIfC3EU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_uGmXX6Pk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_utPgX8hA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_cK9ucvDU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_ZeZu8QhV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iWsXH9Pe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pIXcJ2vz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cmzPEfkn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sBoO1FvS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_flOCJfnO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_AbTYYZOE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aoP3xZx7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7FflU3lv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0GJHY5Lk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oIxuVsnq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UGKDYVI2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IdxNvkpt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3vZteMRU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iqmBZb7O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aId4GUTx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5XgxrFvB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GOgJZRgL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8eVEy7Al_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dyB1mDQj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_B9sX0lQ9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7NeliUc7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cXPHuEcs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uAEzBQTL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XTQTY9Cb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kamMYSrY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QZFeunUz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Z3RBmib2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0jRJjp0d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_MdAGGFnZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LNbTDWEF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F0IQVI6d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4KVE2N4f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ThEGFAkZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hbyRQ0zt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_vvJRTVSO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_cyVnN6TE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_deFPkyO0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nTtKqV7w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EK4vo7dg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5x7W9Etc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zBVCIRI5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2gK7CJpd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IYPgHCrh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kAHAtOKN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yzwGR7Nb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_eP6bEtJO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DyMtiyRr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RPMD2deY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NZ5bNGXY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xPpl2QEo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UyOu1Ss6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MqzXnxEP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_PLadF4GM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_xHrx9b6t_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_3Iq721RA;
  SignalBiquad_k sBiquad_k_nGDESKZU;
  SignalPhasor sPhasor_jheYmMUo;
  SignalPhasor sPhasor_q0quS1iW;
  SignalPhasor sPhasor_P3LuLCLz;
  SignalLine sLine_ZEhsY3GJ;
  ControlDelay cDelay_Yu8ay0lQ;
  ControlVar cVar_Nnfc7x9C;
  ControlBinop cBinop_dWrblezy;
  ControlBinop cBinop_A6MVYCVF;
  ControlBinop cBinop_whoE78sD;
  ControlVar cVar_P3KL6noN;
  ControlVar cVar_eUIKfLve;
  ControlIf cIf_hOFE8kyf;
  ControlBinop cBinop_WuU3C4Lp;
  ControlBinop cBinop_7NQTkXJf;
  ControlRandom cRandom_v7pWLsoa;
  ControlSlice cSlice_TQ5jAajU;
  SignalVari sVari_7VgJQjRv;
  ControlVar cVar_ObOUWnoI;
  ControlVar cVar_mKyLpCkL;
  ControlVar cVar_n2TyQRTN;
  ControlVar cVar_SQRUBity;
  ControlDelay cDelay_u22bsNJt;
  ControlVar cVar_VuUO8pOT;
  ControlBinop cBinop_GUwf6car;
  ControlBinop cBinop_lEGH7x11;
  ControlBinop cBinop_V9kkKiuu;
  ControlVar cVar_b7X8kTRD;
  ControlSlice cSlice_suiSbvgo;
  ControlSlice cSlice_gQaBz8x0;
  ControlVar cVar_1Go5tnsh;
  ControlVar cVar_XyTmFvhx;
  ControlVar cVar_yUmE2zKD;
  ControlVar cVar_kumb9KeP;
  ControlVar cVar_IaKoKe7K;
  ControlSlice cSlice_AUvEPHcH;
  ControlSlice cSlice_9901yvQJ;
  ControlBinop cBinop_miFiRetk;
  ControlBinop cBinop_MnWPJHoa;
  ControlBinop cBinop_OfvUtCed;
  ControlBinop cBinop_RwHb5AJR;
  ControlBinop cBinop_DqCOIhPF;
  ControlBinop cBinop_K7HGzSWC;
  ControlBinop cBinop_6HWKc81T;
  ControlBinop cBinop_mV5g0T3w;
  ControlBinop cBinop_2EhbrWuc;
  ControlBinop cBinop_Cq97QXLx;
  ControlBinop cBinop_xvEgfs4S;
  ControlBinop cBinop_6x8OpbvE;
  ControlBinop cBinop_07Fccqhv;
  ControlRandom cRandom_cBjjgoSs;
  ControlSlice cSlice_sZfVq8jD;
  ControlVar cVar_9qp5BItd;
  ControlVar cVar_R45Qg3wP;
  ControlBinop cBinop_LwzhYklL;
  ControlBinop cBinop_g0xgEbCg;
  ControlBinop cBinop_6vxLx8Vr;
  ControlBinop cBinop_LYXvGp3l;
  ControlBinop cBinop_Wsj5boRx;
  ControlBinop cBinop_eogoMDMN;
  ControlBinop cBinop_K7ebZwft;
  ControlBinop cBinop_5rhoA3ga;
  ControlBinop cBinop_eRBgk2p4;
  ControlBinop cBinop_OAggoaE2;
  ControlBinop cBinop_sBYYDrxv;
  ControlBinop cBinop_yip3Mvj2;
  ControlBinop cBinop_c0YyRIgN;
  ControlBinop cBinop_wmR3cs6y;
  ControlBinop cBinop_shVLnjCS;
  ControlBinop cBinop_NYxrAlj3;
  ControlBinop cBinop_KWQ8SFiE;
  ControlDelay cDelay_3RJCOYcc;
  ControlVar cVar_cZOROno5;
  ControlBinop cBinop_S6u3ul1z;
  ControlBinop cBinop_yDPQIzrg;
  ControlBinop cBinop_PKYneWMg;
  ControlVar cVar_bfBrGQS9;
  ControlSlice cSlice_b5EiwBH6;
  ControlSlice cSlice_JQV7rzsL;
  ControlVar cVar_RNwsu7Qp;
  ControlVar cVar_TqsPRgvJ;
  ControlVar cVar_USNPbtPW;
  ControlVar cVar_FA9HM06u;
  ControlVar cVar_68g9fpZP;
  ControlSlice cSlice_9Rcv20sv;
  ControlSlice cSlice_H5REGhA3;
  ControlBinop cBinop_HOIkovc2;
  ControlBinop cBinop_NWGmmZbL;
  ControlBinop cBinop_HkobI4YQ;
  ControlBinop cBinop_LgjHNIXb;
  ControlBinop cBinop_Id4eDgmg;
  ControlBinop cBinop_8KP0bSZt;
  ControlBinop cBinop_sYjQzHyd;
  ControlBinop cBinop_U8PTT4zA;
  ControlBinop cBinop_kHEXUx6A;
  ControlBinop cBinop_aVLrzYKi;
  ControlBinop cBinop_Z3lEbYEy;
  ControlVar cVar_wYXJkuu3;
  ControlVar cVar_7XMFG1Jx;
  ControlVar cVar_4SrcHYHo;
  ControlBinop cBinop_LZtWDIcT;
  ControlRandom cRandom_JF0BuKA0;
  ControlSlice cSlice_77b0Z3qh;
  ControlBinop cBinop_idOZvx7g;
  ControlRandom cRandom_i9t3pPrX;
  ControlSlice cSlice_khUFGaEr;
  ControlVar cVar_lJiJqIrv;
  ControlBinop cBinop_uqRlI22G;
  ControlDelay cDelay_p7OdiHgQ;
  ControlVar cVar_MBFODPm4;
  ControlBinop cBinop_9vXMw8jJ;
  ControlBinop cBinop_UoyEAKfN;
  ControlBinop cBinop_0QS5SfF7;
  ControlBinop cBinop_tLBIwWgs;
  ControlRandom cRandom_2so6wfvk;
  ControlSlice cSlice_0bPF1CDO;
  ControlDelay cDelay_Cyt5ljfN;
  ControlVar cVar_KZzpRZHu;
  ControlBinop cBinop_ax2bMkL6;
  ControlBinop cBinop_vfQSCO7E;
  ControlBinop cBinop_EaLgdUhr;
  ControlBinop cBinop_VSHSmeue;
  ControlRandom cRandom_YHJH6zTc;
  ControlSlice cSlice_H8WLX0Iq;
  ControlBinop cBinop_K87lg2Hy;
  ControlRandom cRandom_PiQsvku9;
  ControlSlice cSlice_jIX7xxc7;
  ControlDelay cDelay_PqaUaY8t;
  ControlVar cVar_QQ3c7mjd;
  ControlBinop cBinop_LnBVPhpy;
  ControlBinop cBinop_SivKmNdC;
  ControlBinop cBinop_0EEBEXb9;
  ControlVar cVar_OIqXkG1F;
  ControlSlice cSlice_5Qo8DRgA;
  ControlSlice cSlice_8dT8qj1B;
  ControlVar cVar_L86GS0rj;
  ControlVar cVar_pOgk2fvX;
  ControlVar cVar_rRmXwkhu;
  ControlVar cVar_hdQhtWbh;
  ControlVar cVar_BGG0hetm;
  ControlSlice cSlice_y08LbGNS;
  ControlSlice cSlice_ov2A0O1C;
  ControlBinop cBinop_Zkut63Cf;
  ControlBinop cBinop_96fhtK7S;
  ControlBinop cBinop_quEGVJ1U;
  ControlBinop cBinop_QoV1xBwp;
  ControlBinop cBinop_Y9zFco5H;
  ControlBinop cBinop_f28B4zty;
  ControlBinop cBinop_ea3HLll1;
  ControlBinop cBinop_zeg3ioTW;
  ControlBinop cBinop_khxlaUhk;
  ControlBinop cBinop_5P1Hb7z4;
  ControlBinop cBinop_Gqj0ryco;
  ControlVar cVar_NXTkXCSs;
  ControlBinop cBinop_MmUXlvgn;
  ControlVar cVar_OwvzQoYk;
  ControlVar cVar_s8NSUgUT;
  ControlDelay cDelay_9cTclMV7;
  ControlVar cVar_AVMDlWey;
  ControlBinop cBinop_YHtR9sI5;
  ControlBinop cBinop_ZYlNZIe7;
  ControlBinop cBinop_hkTMVp8Q;
  ControlVar cVar_ottfoJXb;
  ControlBinop cBinop_BI6RTa4n;
  ControlDelay cDelay_gRRCpeNl;
  ControlDelay cDelay_li9JZJAJ;
  ControlDelay cDelay_bDp0Em7l;
  ControlDelay cDelay_KYdtSpcr;
  ControlDelay cDelay_QrGvT5Yt;
  ControlDelay cDelay_nvxwvLIr;
  ControlDelay cDelay_S5MaK3OA;
  ControlVar cVar_8CyP6UBV;
  ControlVar cVar_qoAHRdJi;
  ControlVar cVar_u2p8tCx9;
  ControlVar cVar_HkiDCFMJ;
  ControlBinop cBinop_4VgONu0p;
  ControlDelay cDelay_kLoEC4eE;
  ControlVar cVar_U4EkIXYq;
  ControlBinop cBinop_Xh1pArzI;
  ControlBinop cBinop_raPv7gtG;
  ControlBinop cBinop_DF6o1oSK;
  ControlDelay cDelay_ElIMyhI4;
  ControlBinop cBinop_OBSHeIX0;
  ControlRandom cRandom_NjsBlyXK;
  ControlSlice cSlice_pFc3oYz0;
  ControlDelay cDelay_5umfRAyp;
  ControlVar cVar_pS2KruIk;
  ControlBinop cBinop_R30E2bCV;
  ControlBinop cBinop_EK0xFzzX;
  ControlBinop cBinop_chgNfAfk;
  ControlVar cVar_V503mQR2;
  ControlBinop cBinop_cJmF00rT;
  ControlDelay cDelay_J1E6pX7q;
  ControlVar cVar_I3lWjcEm;
  ControlBinop cBinop_AFG1TkyL;
  ControlBinop cBinop_CqpVnGSo;
  ControlRandom cRandom_j8IJW7sl;
  ControlSlice cSlice_pZkf2HDY;
  ControlDelay cDelay_41evEucb;
  ControlDelay cDelay_CZ43RpKE;
  ControlVar cVar_sgz0sbH8;
  ControlBinop cBinop_ic3FAA6P;
  ControlBinop cBinop_CAWdFQ4V;
  ControlBinop cBinop_ZnzomJYv;
  ControlVar cVar_y46Bm6Zu;
  ControlSlice cSlice_psW4eCG8;
  ControlSlice cSlice_7m0Inwpv;
  ControlVar cVar_A9IDcNzF;
  ControlVar cVar_v7M1WUqA;
  ControlVar cVar_lzt4oFBo;
  ControlVar cVar_RNoZ0NsK;
  ControlVar cVar_EZN8BtLf;
  ControlSlice cSlice_HemW1RcB;
  ControlSlice cSlice_MEWQBFaB;
  ControlBinop cBinop_aFhbokg6;
  ControlBinop cBinop_p1hgJmgs;
  ControlBinop cBinop_bIceu0a5;
  ControlBinop cBinop_Q8hCu2ql;
  ControlBinop cBinop_DViOseny;
  ControlBinop cBinop_Zo1wzf0f;
  ControlBinop cBinop_9G2yErcz;
  ControlBinop cBinop_rv88LeR6;
  ControlBinop cBinop_QuUF7Uto;
  ControlBinop cBinop_8zEWHjmM;
  ControlBinop cBinop_oXfbQjHp;
  ControlVar cVar_yxSrksL3;
  ControlBinop cBinop_JFylwJxp;
  ControlRandom cRandom_GbGZkESD;
  ControlSlice cSlice_I86YF72x;
  ControlDelay cDelay_a5wfCUjy;
  ControlVar cVar_PyhZPnaU;
  ControlBinop cBinop_VT7Ojn4h;
  ControlBinop cBinop_jHFUXb03;
  ControlBinop cBinop_Gk65LOcD;
  ControlVar cVar_YrGju7j8;
  ControlBinop cBinop_JuTMwHW7;
  ControlDelay cDelay_7U1bb9hT;
  ControlVar cVar_ZZUedFlg;
  ControlBinop cBinop_Iq8wPRXE;
  ControlBinop cBinop_5PvoTscH;
  ControlRandom cRandom_psO9A26B;
  ControlSlice cSlice_ecqJ4sfE;
  ControlDelay cDelay_2vxR4c2p;
  ControlDelay cDelay_pIKdjt2k;
  ControlVar cVar_HZC1ip7W;
  ControlBinop cBinop_Vz02BJP2;
  ControlBinop cBinop_5l3EpQ0c;
  ControlBinop cBinop_NmPYD90t;
  ControlVar cVar_eOO7M87x;
  ControlSlice cSlice_xWoOn2P4;
  ControlSlice cSlice_35rqWCye;
  ControlVar cVar_8np9dfCS;
  ControlVar cVar_yC2Epoyf;
  ControlVar cVar_tPIfC3EU;
  ControlVar cVar_uGmXX6Pk;
  ControlVar cVar_utPgX8hA;
  ControlSlice cSlice_cK9ucvDU;
  ControlSlice cSlice_ZeZu8QhV;
  ControlBinop cBinop_iWsXH9Pe;
  ControlBinop cBinop_pIXcJ2vz;
  ControlBinop cBinop_cmzPEfkn;
  ControlBinop cBinop_sBoO1FvS;
  ControlBinop cBinop_flOCJfnO;
  ControlBinop cBinop_7FflU3lv;
  ControlBinop cBinop_0GJHY5Lk;
  ControlBinop cBinop_oIxuVsnq;
  ControlBinop cBinop_UGKDYVI2;
  ControlBinop cBinop_8eVEy7Al;
  ControlBinop cBinop_XTQTY9Cb;
  ControlVar cVar_MdAGGFnZ;
  ControlBinop cBinop_LNbTDWEF;
  ControlBinop cBinop_F0IQVI6d;
  ControlBinop cBinop_hbyRQ0zt;
  SignalVarf sVarf_OQxdukrC;
  ControlBinop cBinop_nTtKqV7w;
  ControlBinop cBinop_5x7W9Etc;
  ControlBinop cBinop_zBVCIRI5;
  ControlBinop cBinop_2gK7CJpd;
  SignalVarf sVarf_Ie4VYlva;
  SignalVarf sVarf_nw3eEMj2;
  SignalVarf sVarf_ewXMsNMW;
  SignalVarf sVarf_jmhQqPsJ;
  SignalVarf sVarf_zMC2F8vL;
};

#endif // _HEAVY_CONTEXT_GRILLOSYCHICHARRASOSC_HPP_
